name: Publish Docker Image

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REPOSITORY: ${{ secrets.DOCKER_HUB_ORGS }}/fluentd-kubernetes-daemonset
    strategy:
      fail-fast: false
      matrix:
        context:
          - docker-image/v1.16/arm64/debian-azureblob
          - docker-image/v1.16/arm64/debian-cloudwatch

    steps:
      - uses: actions/checkout@v4
      - name: Setup tags
        run: |
          context=docker-image/v1.16/arm64/debian-azureblob
          component=${context##*/}
          for target in $(make echo-all-images); do
            case $target in
              *$component-amd64*)
                tags=$(echo $target | cut -d':' -f2-)
                tag1=$(echo $tags | cut -d',' -f1)
                tag2=$(echo $tags | cut -d',' -f2)
                echo $tag1
                echo $tag2
                ;;
              *$component-arm64*)
                tags=$(echo $target | cut -d':' -f2-)
                tag1=$(echo $tags | cut -d',' -f1)
                tag2=$(echo $tags | cut -d',' -f2)
                echo $tag1
                echo $tag2
                ;;
            esac
          done
