name: Publish Docker Image

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REPOSITORY: ${{ secrets.DOCKER_HUB_ORGS }}/fluentd-kubernetes-daemonset
    strategy:
      fail-fast: false
      matrix:
        context:
          - docker-image/v1.16/arm64/debian-azureblob
          - docker-image/v1.16/arm64/debian-cloudwatch
          - docker-image/v1.16/arm64/debian-elasticsearch7
          - docker-image/v1.16/arm64/debian-elasticsearch8
          - docker-image/v1.16/arm64/debian-forward
          - docker-image/v1.16/arm64/debian-gcs
          - docker-image/v1.16/arm64/debian-graylog
          - docker-image/v1.16/arm64/debian-kafka
          - docker-image/v1.16/arm64/debian-kafka2
          - docker-image/v1.16/arm64/debian-kinesis
          - docker-image/v1.16/arm64/debian-logentries
          - docker-image/v1.16/arm64/debian-loggly
          - docker-image/v1.16/arm64/debian-logzio
          - docker-image/v1.16/arm64/debian-opensearch
          - docker-image/v1.16/arm64/debian-papertrail
          - docker-image/v1.16/arm64/debian-s3
          - docker-image/v1.16/arm64/debian-syslog

    steps:
      - uses: actions/checkout@v4
      - name: Setup tags
        run: |
          context=docker-image/v1.16/arm64/debian-azureblob
          component=${context##*/}
          for target in $(make echo-all-images); do
            case $target in
              *$component-amd64*)
                tags=$(echo $target | cut -d':' -f2-)
                tag1=$(echo $tags | cut -d',' -f1)
                tag2=$(echo $tags | cut -d',' -f2)
                echo $tag1
                echo $tag2
                ;;
              *$component-arm64*)
                tags=$(echo $target | cut -d':' -f2-)
                tag1=$(echo $tags | cut -d',' -f1)
                tag2=$(echo $tags | cut -d',' -f2)
                echo $tag1
                echo $tag2
                ;;
            esac
          done
